version: '3.9'
services:
  backend:
    build:
      context: ../..
      dockerfile: apps/be/Dockerfile
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '8081:8081'
    networks:
      - zyme-network

  database:
    image: 'postgres:16'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'zyme'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    networks:
      - zyme-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - zyme-network

networks:
  zyme-network:
    driver: bridge