blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://chat.zyme.dev
    about: Ask questions and discuss with other Zyme users in real time.
  - name: Questions & Discussions
    url: https://github.com/mohsenshafiei/zyme/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
