// Utils
import { cx } from "class-variance-authority";

// Styles
import "@/style/globals.css";
import globalFontsVariables from "@/fonts";

// Types
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cx(globalFontsVariables, "scroll-smooth dark")}>
      <body>{children}</body>
    </html>
  );
}
