name: ci

on:
  push:
    branches:
      - feat/git-actions
  pull_request:
    branches: [ $default-branch ]

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
              ref: feat/git-actions
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"     
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@v4
 