name: zyme CI

on:
  push:
    branches:
      - feat/git-actions
  pull_request:
    branches: [ $default-branch ]

jobs:
  install:
      runs-on: ubuntu-latest 
      steps:
        - uses: actions/checkout@v4
          with: 
                ref: feat/git-actions
      
        - name: Install dependencies
          run: npm i
  test:
      runs-on: ubuntu-latest 
      needs: install
      steps:
        - uses: actions/checkout@v4
          with: 
                ref: feat/git-actions
      
        - name: test
          run: npm run test
  build:
      runs-on: ubuntu-latest 
      needs: test
      steps:
        - uses: actions/checkout@v4
          with: 
                ref: feat/git-actions
      
        - name: Build Project
          run: npm build